### ISSUE TITLE
Arquitetura e Configuração

### ISSUE THREAD

**Issue by LuizLimaDev** [LuizLimaDev/front-back-montain-backend#1]
1. Criar o projeto com Node.
2. Configurar o ESlint.
3. Intalar as bibliotecas.

**Arquitetura  **
Pastas: 
- controllers
- database
- middlewares
- schemas
- routes

**Bibliotecas**
- express
- nodemon (desenvolvimento)
- dotenv (desenvolvimento)
- bcrypt
- jsonwebtoken

**Comment by Fernanda-Campelo** [comment]
Tarefa realizada. Foram instaladas as bibliotecas knex, joi, cors e dotenv, além do que foi especificado na issue.

**Comment by LuizLimaDev** [comment]
Feito!
