### ISSUE TITLE
Input de pesquisas na página clientes só mostra o resultado com nomes exatos

### ISSUE THREAD

**Issue by Engenuis** [LuizLimaDev/front-back-montain-backend#53]
- Deve ser possível no campo de pesquisas, encontrar clientes com apenas poucos caracteres de pesquisa e não com nomes exatos.
 - Sugestão: Usar o método includes() de Strings transformando, tanto a string de pesquisa, quanto os itens pesquisados em LowerCase(), executando trim() nos dois.

**Comment by Amandalfs** [comment]
nao estou usando funcoes padroes do js, esstou usando queries do sql mas ja vou arrumar
