### ISSUE TITLE
[Ordenação de Cobranças] bugs: ordenação errada por conta de maiúsculas e minúsculas

### ISSUE THREAD

**Issue by Edualct** [LuizLimaDev/front-back-montain-backend#63]
**Descreva o bug**
Ao ordenar a tabela de cobranças por ordem alfabética, ela faz a distinção entre letras maiúscula e minúscula, deixando fora de ordem.

**Reproduzir**
Etapas para reproduzir o comportamento:

Vá para 'Cobranças'
Clique nas setas ao lado de cliente.
Observe que a lista é ordenada primeiro em quem tem letra maiuscula e depois do ultimo começa a ordenação em letras minúsculas.
Veja o er

![Captura de Tela 2023-10-02 às 17 17 41](https://github.com/LuizLimaDev/front-back-mountain-backend/assets/117872518/a23a8597-51f1-4c26-b33e-9697e05d537d)
ro

**Comportamento esperado**
Devem estar ordenadas em ordem alfabética.

**Comment by LuizLimaDev** [comment]
Esta issue será resolvida no Frontend.
